### ISSUE TITLE
TODOs and TODOnts

### ISSUE THREAD

**Issue by dotmbf** [Sledmore/PlusEMU#3]
I left you some TODOs in the code, I'll swag 'em up here instead! You just say the word and I'll fix them up, nice and tidy.
https://github.com/Sledmore/PlusEMU/blob/master/Communication/Packets/Outgoing/Navigator/New/NavigatorPreferencesComposer.cs#L8
https://github.com/Sledmore/PlusEMU/blob/master/Communication/Packets/Outgoing/Navigator/New/NavigatorMetaDataParserComposer.cs#L12
@Sledmore

**Comment by dotmbf** [comment]
Also in my current PR i left a comment:
https://github.com/mikkelbfriis/PlusEMU-1/blob/a23a6c086e0ed85db81aa5579811214596f28e57/HabboHotel/Users/Inventory/InventoryComponent.cs#L247

**Comment by Sledmore** [comment]
I think that comment may have been left a while ago, and never removed. Also, just a note, I'll be a little more active on this soon enough. Thanks for your work so far though!

**Comment by Sledmore** [comment]
Appreciate you going through this, will go through your notes. I think I'm gonna swing back into this now. Just there is clearly a lot to do haha.

**Comment by Sledmore** [comment]
Scrap that, gone through them now.

https://github.com/Sledmore/PlusEMU/blob/master/Communication/Packets/Outgoing/Navigator/New/NavigatorPreferencesComposer.cs#L8
https://github.com/Sledmore/PlusEMU/blob/master/Communication/Packets/Outgoing/Navigator/New/NavigatorMetaDataParserComposer.cs#L12

Feel free to do the above, I guess adding them would make it more feature complete. Just never got to it at the time!

I've pushed a tweak for the pet one now, just personal preference! Checking if it adds properly to the inventory, then changing the values.

https://github.com/Sledmore/PlusEMU/commit/0827018120e85814a774eb25905cc1eafe27e2ba

Cheers.

**Comment by dotmbf** [comment]
@Sledmore Care to answer me on Discord so we could chat about the future of this project?

**Comment by dotmbf** [comment]
i am spoderman btw.
