### ISSUE TITLE
Navigator Disconnection

### ISSUE THREAD

**Issue by Diddyy** [Sledmore/PlusEMU#6]
Currently when opening the navigator it will disconnect the user.
This is with the fresh DB provided. 

The only way around this at the moment is going to Profile > Rooms and then you can enter a room, however clicking public or my world will disconnect. 

Can not seem to find a solution at the moment? @Sledmore 

Also no errors are logged

https://gyazo.com/18eebd4629705671700b1d2765571c0c

**Comment by Sledmore** [comment]
Very late reply, but possibly an issue with an entry existing in navigator_publics but no room existing. Will look into it.

**Comment by dotmbf** [comment]
@Diddyy as @Sledmore said, might be an issue with no room existing, can you post your navigator_publics and find the entry for the room?

**Comment by Diddyy** [comment]
@Sledmore navigator_publics is empty but when clicking it in dev log ```errorCode = Failed to parse incoming message using_-0WH::_-0KW``` is now logged

**Comment by Sledmore** [comment]
Ah okay, incorrect structure somewhere then. Will look into this when I'm home.

**Comment by dotmbf** [comment]
It’s not. It’s when an outgoing packet is nulled, for example, when a room isn’t properly setup as a public room.
However, this issue should be handled code wise, so probably some NPE checks should be added? @Sledmore

**Comment by ghost** [comment]
I have the exact same issue. (Clean DB from Resources/SQL)

Edit --> @mikkelbfriis @Sledmore @Diddyy --> i can get in navigator when i use the player menu. Opening it by PUBLICS just doesnt work AT ALL.

**Comment by dotmbf** [comment]
@PepijnGamerz exactly my point.

**Comment by dotmbf** [comment]
Database issue.

**Comment by ghost** [comment]
Solution: truncate table navigator_categories... rooms doesnt appear but navigator works

PS: I can't make a room, everything turns black

**Comment by samondrugs** [comment]
This is nothing to do with the database, its because one of the case statements isn't handled, in NavigationManager for category_type I believe

**Comment by deactivated-b419f** [comment]
This has nothing to do with the database, it's because you're not handling the category_type of one of your database entries in NavigationManager.cs I beleive.

Black room is probably due to the columns @Sledmore didn't add to the SQL, sale_price and I forgot the other one in rooms table.

**Comment by Sledmore** [comment]
Sorry to bump such an old issue, this is actually to do with the packet structure as originally stated. Not sure how I ever oversaw this, but an integer was missing for three different cases in the NavigatorHandler.

https://github.com/Sledmore/PlusEMU/pull/15/commits/97243ff2051854f7a6eadeb0b7a2e0baf39dbfea

**Comment by Sledmore** [comment]
Also, the chap above is correct that two columns in the `rooms` table are missing, run the following to resolve that.

```sql
ALTER TABLE `rooms` 
ADD COLUMN `sale_price` int(11) NULL DEFAULT 0 AFTER `spush_enabled`,
ADD COLUMN `lay_enabled` enum('0','1') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '1' AFTER `sale_price`;
```

**Comment by Jmandupree** [comment]
Hmm, Tend to still have the same error.. I cleared the nav_cat in DB and navigator opens click create room and D/C..

`errorCode = Error in update receiver "com.sulake.bootstrap::HabboWindowManagerComponentBootstrap": Error: Menu selection index out of range!`
